server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/yms
    username: yms_user
    password: yms_clave
    driver-class-name: com.mysql.cj.jdbc.Driver
